[client]
showSidebarNavigation = false

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false

# Hide the hamburger menu
[server]
headless = true

# Additional customization
[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
