[client]
showSidebarNavigation = false

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false

# Hide the hamburger menu
[server]
headless = true

# Dark mode theme
[theme]
base = "dark"
primaryColor = "#4dabf7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
